apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: library-mern
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ldavis007/chat-mern-backend:latest   # cámbialo por tu repo de DockerHub o GHCR
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-env
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
