services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: library_mern_nginx
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      MONGO_DB_URI: ${MONGO_DB_URI}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - library-mern-api
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: library_mern_frontend
    environment:
      VITE_API_URL: ${VITE_API_URL}  # Pasar la URL del backend al frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - library-mern-api
  nginx:
    restart: always
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - library-mern-api
networks:
  library-mern-api:
    driver: bridge
