services:
  mongo:
    image: mongo:7.0
    container_name: library_mern_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - library-mern-api
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: library_mern_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - library-mern-api

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: library_mern_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - library-mern-api

  nginx:
    restart: always
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - library-mern-api

networks:
  library-mern-api:
    driver: bridge
