apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: library-mern
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer   # usa NodePort si no tienes un cloud provider
