apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: library-mern
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  clusterIP: None   # Headless Service, necesario para StatefulSet
  selector:
    app: mongo
